"""add visit

Revision ID: d9dda16f4953
Revises: 68779271bae4
Create Date: 2020-02-21 18:00:31.638054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9dda16f4953'
down_revision = '68779271bae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
    	batch_op.drop_column('enter_time')
    	batch_op.drop_column('exit_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('exit_time', sa.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('enter_time', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
